package com.gp.database;

/**
 * Created by Administrator on 2016/10/11.
 */
public class DBConstant {
    public static final int type_0 =0;//深圳
    public static final int type_6 =6;//上海
    public static final String _id                             ="_id";
    public static final String uid                            ="uid";
    public static final String gp_uid                         ="gp_uid";
    public static final String create_time                   ="create_time";
    public static final String update_time                   ="update_time";
    public static final String type                           ="type";
    public static final String status                         ="status";
    public static final String sort                         ="sort";
    public static final String gp_year                        ="gp_year";
    public static final String gp_month                           ="gp_month";
    public static final String gp_day                         ="gp_day";
    public static final String gpstr                          ="gpstr";
    public static final String name                           ="name";
    public static final String code                           ="code";
    public static final String now_price                      ="now_price";
    public static final String zuo_price                      ="zuo_price";
    public static final String jin_price                      ="jin_price";
    public static final String total_volume                 ="total_volume";
    public static final String wai_num                    ="wai_num";
    public static final String nei_num                    ="nei_num";
    public static final String buy_price                  ="buy_price";
    public static final String buy_volume                 ="buy_volume";
    public static final String buy2_price                 ="buy2_price";
    public static final String buy2_volume                ="buy2_volume";
    public static final String buy3_price                 ="buy3_price";
    public static final String buy3_volume                ="buy3_volume";
    public static final String buy4_price                 ="buy4_price";
    public static final String buy4_volume                ="buy4_volume";
    public static final String buy5_price                         ="buy5_price";
    public static final String buy5_volume                   ="buy5_volume";
    public static final String sell_price                     ="sell_price";
    public static final String sell_volume                ="sell_volume";
    public static final String sell2_price              ="sell2_price";
    public static final String sell2_volume              ="sell2_volume";
    public static final String sell3_price              ="sell3_price";
    public static final String sell3_volume              ="sell3_volume";
    public static final String sell4_price                   ="sell4_price";
    public static final String sell4_volume                   ="sell4_volume";
    public static final String sell5_price                   ="sell5_price";
    public static final String sell5_volume                   ="sell5_volume";
    public static final String recent_trade                   ="recent_trade";
    public static final String recent_time                   ="recent_time";
    public static final String change_price                   ="change_price";
    public static final String change_price_percent              ="change_price_percent";
    public static final String max_price                    ="max_price";
    public static final String min_price                        ="min_price";
    public static final String last_price                   ="last_price";
    public static final String last_volume_num              ="last_volume_num";
    public static final String last_volume_price              ="last_volume_price";
    public static final String huan_shou_lv              ="huan_shou_lv";
    public static final String shi_ying_lv_ttm              ="shi_ying_lv_ttm";
    public static final String ziduan1                          ="ziduan1";
    public static final String max_price2                   ="max_price2";
    public static final String min_price2                   ="min_price2";
    public static final String zhen_fu                          ="zhen_fu";
    public static final String liutong_shizhi              ="liutong_shizhi";
    public static final String total_shizhi              ="total_shizhi";
    public static final String shi_jing_lv              ="shi_jing_lv";
    public static final String top_price                    ="top_price";
    public static final String bottom_price              ="bottom_price";
    public static final String liang_bi                     ="liang_bi";
    public static final String ziduan2                      ="ziduan2";
    public static final String average_price              ="average_price";
    public static final String shi_ying_lv_dong              ="shi_ying_lv_dong";
    public static final String shi_ying_lv_jing              ="shi_ying_lv_jing";
}
